window.EXPLANATIONS_BY_PROMPT = {
  "La virtualisation consiste a :": "La virtualisation consiste a emuler une architecture materielle physique pour creer une ou plusieurs architectures logiques, appelees machines virtuelles. Un meme serveur physique peut donc heberger plusieurs environnements virtuels.",
  "La virtualisation permet a un seul serveur physique d'heberger plusieurs machines virtuelles.": "La virtualisation consiste a emuler une architecture materielle physique pour creer une ou plusieurs architectures logiques, appelees machines virtuelles. Un meme serveur physique peut donc heberger plusieurs environnements virtuels.",
  "Les 4 ressources principales virtualisees sont :": "Les quatre ressources principales virtualisees sont le processeur (CPU), la memoire vive (RAM), le stockage et le reseau. Ce sont les ressources que l'hyperviseur repartit entre les machines virtuelles.",
  "Quelles ressources sont virtualisees ?": "Les quatre ressources principales virtualisees sont le processeur (CPU), la memoire vive (RAM), le stockage et le reseau. Ce sont les ressources que l'hyperviseur repartit entre les machines virtuelles.",
  "Une machine virtuelle est :": "Une machine virtuelle est un ordinateur logique constitue d'un ensemble de fichiers. Elle simule un vrai ordinateur avec un systeme d'exploitation, de la memoire, du processeur, du stockage et du reseau.",
  "L'hyperviseur permet de :": "L'hyperviseur sert a creer, executer et administrer les machines virtuelles. Il fait le lien entre le materiel physique et les environnements virtuels.",
  "Le role principal de l'hyperviseur est de :": "L'hyperviseur sert a creer, executer et administrer les machines virtuelles. Il fait le lien entre le materiel physique et les environnements virtuels.",
  "Un hyperviseur de type 1 s'installe :": "Un hyperviseur de type 1 s'installe directement sur le materiel physique, sans systeme d'exploitation classique. VMware ESXi, Hyper-V Server et Proxmox VE sont des hyperviseurs de type 1, souvent utilises en production.",
  "Lequel est un hyperviseur de type 1 ?": "Un hyperviseur de type 1 s'installe directement sur le materiel physique, sans systeme d'exploitation classique. VMware ESXi, Hyper-V Server et Proxmox VE sont des hyperviseurs de type 1, souvent utilises en production.",
  "VMware ESXi est surtout utilise :": "Un hyperviseur de type 1 s'installe directement sur le materiel physique, sans systeme d'exploitation classique. VMware ESXi, Hyper-V Server et Proxmox VE sont des hyperviseurs de type 1, souvent utilises en production.",
  "Quels sont des hyperviseurs de type 1 ?": "Un hyperviseur de type 1 s'installe directement sur le materiel physique, sans systeme d'exploitation classique. VMware ESXi, Hyper-V Server et Proxmox VE sont des hyperviseurs de type 1, souvent utilises en production.",
  "Un hyperviseur de type 1 s'installe sur un systeme Windows deja installe.": "Un hyperviseur de type 1 s'installe directement sur le materiel physique, sans systeme d'exploitation classique. VMware ESXi, Hyper-V Server et Proxmox VE sont des hyperviseurs de type 1, souvent utilises en production.",
  "Un hyperviseur de type 2 s'installe :": "Un hyperviseur de type 2 s'installe sur un systeme d'exploitation existant, comme Windows ou Linux. Il est surtout utilise pour les tests, la formation ou les environnements de labo, comme VMware Workstation ou VirtualBox.",
  "Lequel est un hyperviseur de type 2 ?": "Un hyperviseur de type 2 s'installe sur un systeme d'exploitation existant, comme Windows ou Linux. Il est surtout utilise pour les tests, la formation ou les environnements de labo, comme VMware Workstation ou VirtualBox.",
  "Un hyperviseur de type 2 est surtout utilise pour :": "Un hyperviseur de type 2 s'installe sur un systeme d'exploitation existant, comme Windows ou Linux. Il est surtout utilise pour les tests, la formation ou les environnements de labo, comme VMware Workstation ou VirtualBox.",
  "Quelle difference est correcte entre type 1 et type 2 ?": "La difference entre un hyperviseur de type 1 et de type 2 est simple : le type 1 s'installe directement sur le materiel, alors que le type 2 s'installe sur un systeme d'exploitation existant.",
  "Tu veux un environnement de test sur ton PC personnel Windows. Quelle solution est la plus adaptee ?": "Pour un environnement de test sur un PC personnel, un hyperviseur de type 2 comme VMware Workstation ou VirtualBox est le plus adapte. Ces solutions sont concues pour fonctionner sur un systeme existant.",
  "Le VMkernel est :": "Le VMkernel est le noyau principal de VMware ESXi. Il gere le CPU, la RAM, le stockage et le reseau, et fait le lien entre le materiel physique et les machines virtuelles.",
  "Le role du VMkernel est de :": "Le VMkernel est le noyau principal de VMware ESXi. Il gere le CPU, la RAM, le stockage et le reseau, et fait le lien entre le materiel physique et les machines virtuelles.",
  "VMkernel signifie :": "Le VMkernel est le noyau principal de VMware ESXi. Il gere les ressources physiques et permet leur utilisation par les machines virtuelles.",
  "Quelles affirmations sur le VMkernel sont vraies ?": "Le VMkernel est le noyau principal de VMware ESXi. Il gere le CPU, la RAM, le stockage et le reseau, et fait le lien entre le materiel physique et les machines virtuelles.",
  "La RAM physique attribuee a une machine virtuelle devient :": "La RAM physique allouee a une machine virtuelle devient de la vRAM, c'est-a-dire de la memoire vive virtuelle.",
  "Le processeur virtuel d'une VM est appele :": "Le processeur virtuel d'une machine virtuelle s'appelle un vCPU. Il correspond a une ressource processeur presentee a la VM par l'hyperviseur.",
  "L'hote correspond a :": "L'hote est le serveur physique ou l'hyperviseur qui heberge les machines virtuelles. C'est la machine qui fournit les ressources materielles.",
  "L'invite correspond a :": "L'invite est le systeme d'exploitation installe a l'interieur de la machine virtuelle. Par exemple, Windows Server, Ubuntu ou Debian peuvent etre des systemes invites.",
  "SAN signifie :": "SAN signifie Storage Area Network. C'est un reseau dedie au stockage qui permet aux serveurs d'acceder a des ressources de stockage centralisees comme s'il s'agissait de disques locaux. Il est surtout utilise pour du stockage bloc performant cote serveurs.",
  "Un SAN permet :": "SAN signifie Storage Area Network. C'est un reseau dedie au stockage qui permet aux serveurs d'acceder a des ressources de stockage centralisees comme s'il s'agissait de disques locaux. Il est surtout utilise pour du stockage bloc performant cote serveurs.",
  "Le SAN est plutot oriente :": "SAN signifie Storage Area Network. C'est un reseau dedie au stockage qui permet aux serveurs d'acceder a des ressources de stockage centralisees comme s'il s'agissait de disques locaux. Il est surtout utilise pour du stockage bloc performant cote serveurs.",
  "Le SAN se distingue surtout du NAS car :": "SAN signifie Storage Area Network. C'est un reseau dedie au stockage qui permet aux serveurs d'acceder a des ressources de stockage centralisees comme s'il s'agissait de disques locaux. Il est surtout utilise pour du stockage bloc performant cote serveurs.",
  "Le SAN permet aux serveurs d'acceder a du stockage comme s'il etait local.": "SAN signifie Storage Area Network. C'est un reseau dedie au stockage qui permet aux serveurs d'acceder a des ressources de stockage centralisees comme s'il s'agissait de disques locaux. Il est surtout utilise pour du stockage bloc performant cote serveurs.",
  "Quelle difference est correcte entre SAN et NAS ?": "La difference principale entre SAN et NAS est la suivante : le SAN fournit un stockage de type bloc vu comme local par les serveurs, alors que le NAS fournit surtout un stockage reseau oriente partage de fichiers.",
  "Tu veux fournir a des serveurs un stockage performant vu comme local. Quel choix correspond le mieux ?": "Si l'objectif est de fournir a des serveurs un stockage performant vu comme local, la solution adaptee est le SAN.",
  "NAS signifie :": "NAS signifie Network Attached Storage. C'est un appareil ou serveur de stockage connecte au reseau, surtout utilise pour le partage de fichiers, les sauvegardes et le stockage centralise accessible par plusieurs utilisateurs ou machines.",
  "Un NAS est surtout utilise pour :": "NAS signifie Network Attached Storage. C'est un appareil ou serveur de stockage connecte au reseau, surtout utilise pour le partage de fichiers, les sauvegardes et le stockage centralise accessible par plusieurs utilisateurs ou machines.",
  "Le NAS est plutot oriente :": "NAS signifie Network Attached Storage. C'est un appareil ou serveur de stockage connecte au reseau, surtout utilise pour le partage de fichiers, les sauvegardes et le stockage centralise accessible par plusieurs utilisateurs ou machines.",
  "Le NAS est surtout utilise pour le partage de fichiers sur un reseau.": "NAS signifie Network Attached Storage. C'est un appareil ou serveur de stockage connecte au reseau, surtout utilise pour le partage de fichiers, les sauvegardes et le stockage centralise accessible par plusieurs utilisateurs ou machines.",
  "Tu veux partager simplement des fichiers entre plusieurs utilisateurs sur le reseau. Quel choix correspond le mieux ?": "Si l'objectif est de partager simplement des fichiers entre plusieurs utilisateurs ou machines sur le reseau, le choix le plus adapte est le NAS.",
  "Dans ESXi, l'espace de stockage logique utilise pour les VM s'appelle :": "Dans ESXi, un datastore est un espace de stockage logique utilise pour enregistrer les fichiers des machines virtuelles. Il peut contenir les disques virtuels, les fichiers de configuration, les snapshots, les fichiers de swap et d'autres fichiers lies aux VM.",
  "Un datastore peut contenir :": "Dans ESXi, un datastore est un espace de stockage logique utilise pour enregistrer les fichiers des machines virtuelles. Il peut contenir les disques virtuels, les fichiers de configuration, les snapshots, les fichiers de swap et d'autres fichiers lies aux VM.",
  "Le datastore est :": "Dans ESXi, un datastore est un espace de stockage logique utilise pour enregistrer les fichiers des machines virtuelles. Il peut contenir les disques virtuels, les fichiers de configuration, les snapshots, les fichiers de swap et d'autres fichiers lies aux VM.",
  "Le datastore :": "Dans ESXi, un datastore est un espace de stockage logique utilise pour enregistrer les fichiers des machines virtuelles. Il peut contenir les disques virtuels, les fichiers de configuration, les snapshots, les fichiers de swap et d'autres fichiers lies aux VM.",
  "Quels elements peuvent se trouver dans un datastore ?": "Dans ESXi, un datastore est un espace de stockage logique utilise pour enregistrer les fichiers des machines virtuelles. Il peut contenir les disques virtuels, les fichiers de configuration, les snapshots, les fichiers de swap et d'autres fichiers lies aux VM.",
  "FQDN signifie :": "FQDN signifie Fully Qualified Domain Name. C'est le nom de domaine complet d'une machine sur un reseau ou sur Internet, par exemple www.google.com.",
  "Dans le FQDN www.google.com :": "FQDN signifie Fully Qualified Domain Name. C'est le nom de domaine complet d'une machine sur un reseau ou sur Internet, par exemple www.google.com.",
  "Le fichier .vmx correspond :": "Le fichier .vmx est le fichier de configuration principal de la machine virtuelle. Il contient les parametres de la VM comme la RAM, le CPU, le reseau, les disques, et c'est ce fichier qu'on charge dans l'inventaire VMware pour administrer la VM.",
  "Le fichier principal a utiliser pour enregistrer une VM dans l'inventaire est :": "Le fichier .vmx est le fichier de configuration principal de la machine virtuelle. Il contient les parametres de la VM comme la RAM, le CPU, le reseau, les disques, et c'est ce fichier qu'on charge dans l'inventaire VMware pour administrer la VM.",
  "Une machine virtuelle apparait dans l'interface d'administration grace :": "Le fichier .vmx est le fichier de configuration principal de la machine virtuelle. Il contient les parametres de la VM comme la RAM, le CPU, le reseau, les disques, et c'est ce fichier qu'on charge dans l'inventaire VMware pour administrer la VM.",
  "VMX signifie :": "Le fichier .vmx est le fichier de configuration principal de la machine virtuelle. Il contient les parametres essentiels de la VM.",
  "Le fichier .vmx contient :": "Le fichier .vmx est le fichier de configuration principal de la machine virtuelle. Il contient les parametres de la VM comme la RAM, le CPU, le reseau, les disques, et c'est ce fichier qu'on charge dans l'inventaire VMware pour administrer la VM.",
  "Quel fichier faut-il utiliser pour enregistrer une VM presente dans un datastore dans l'interface VMware ?": "Le fichier .vmx est le fichier de configuration principal de la machine virtuelle. Il contient les parametres de la VM comme la RAM, le CPU, le reseau, les disques, et c'est ce fichier qu'on charge dans l'inventaire VMware pour administrer la VM.",
  "Le fichier .vmx contient les donnees reelles du disque virtuel.": "Le fichier .vmx est le fichier de configuration principal de la machine virtuelle. Il contient les parametres de la VM comme la RAM, le CPU, le reseau, les disques, et c'est ce fichier qu'on charge dans l'inventaire VMware pour administrer la VM.",
  "Le fichier .vmdk correspond :": "Le fichier .vmdk represente le disque virtuel de la machine virtuelle. Dans VMware, il correspond au disque de la VM, meme si les donnees reelles peuvent etre stockees dans un fichier -flat.vmdk associe.",
  "VMDK signifie :": "VMDK signifie Virtual Machine Disk. C'est le format de disque virtuel utilise par VMware.",
  "Le fichier -flat.vmdk contient :": "Le fichier -flat.vmdk contient les donnees reelles du disque virtuel. C'est lui qui occupe reellement l'espace de stockage sur le datastore.",
  "Le fichier qui contient reellement les donnees du disque virtuel est :": "Le fichier -flat.vmdk contient les donnees reelles du disque virtuel. C'est lui qui occupe reellement l'espace de stockage sur le datastore.",
  "Le fichier -flat.vmdk :": "Le fichier -flat.vmdk contient les donnees reelles du disque virtuel. C'est lui qui occupe reellement l'espace de stockage sur le datastore.",
  "Le fichier -flat.vmdk contient les donnees reelles du disque virtuel.": "Le fichier -flat.vmdk contient les donnees reelles du disque virtuel. C'est lui qui occupe reellement l'espace de stockage sur le datastore.",
  "Le fichier .nvram contient :": "NVRAM signifie Non-Volatile Random Access Memory. Le fichier .nvram contient les parametres BIOS ou UEFI de la machine virtuelle.",
  "Le BIOS ou l'UEFI d'une VM est stocke dans :": "NVRAM signifie Non-Volatile Random Access Memory. Le fichier .nvram contient les parametres BIOS ou UEFI de la machine virtuelle.",
  "NVRAM signifie :": "NVRAM signifie Non-Volatile Random Access Memory. Dans VMware, le fichier .nvram contient les parametres BIOS/UEFI de la VM.",
  "Le fichier .nvram stocke :": "NVRAM signifie Non-Volatile Random Access Memory. Le fichier .nvram contient les parametres BIOS ou UEFI de la machine virtuelle.",
  "Le fichier .nvram contient les parametres BIOS/UEFI de la VM.": "NVRAM signifie Non-Volatile Random Access Memory. Le fichier .nvram contient les parametres BIOS ou UEFI de la machine virtuelle.",
  "Le fichier .vswp est :": "Le fichier .vswp est le fichier de swap VMware. Il sert d'espace temporaire de memoire sur disque lorsque l'hyperviseur en a besoin pour la gestion memoire de la VM.",
  "VSWP signifie :": "VSWP signifie Virtual Machine Swap. C'est le fichier de swap utilise par VMware pour la machine virtuelle.",
  "Le swap VMware est gere par :": "Le fichier .vswp est le fichier de swap VMware. Il sert d'espace temporaire de memoire sur disque lorsque l'hyperviseur en a besoin pour la gestion memoire de la VM.",
  "Dans VMware, le fichier .vswp est :": "Dans VMware, le fichier .vswp est cree au demarrage de la machine virtuelle et supprime a son arret. C'est le fichier de swap propre a la VM.",
  "Quelles affirmations sur le fichier .vswp sont vraies ?": "Dans VMware, le fichier .vswp est cree au demarrage de la machine virtuelle et supprime a son arret. C'est le fichier de swap propre a la VM.",
  "Le fichier .vswp existe uniquement quand la VM est allumee.": "Dans VMware, le fichier .vswp est cree au demarrage de la machine virtuelle et supprime a son arret. C'est le fichier de swap propre a la VM.",
  "Le fichier .vmss sert a :": "VMSS signifie Virtual Machine Suspend State. Le fichier .vmss enregistre l'etat d'une machine virtuelle lorsqu'elle est suspendue, pour pouvoir la reprendre plus tard dans le meme etat.",
  "VMSS signifie :": "VMSS signifie Virtual Machine Suspend State. Ce fichier enregistre l'etat d'une VM suspendue.",
  "Le fichier .vmss est utilise lorsque la VM est :": "VMSS signifie Virtual Machine Suspend State. Le fichier .vmss enregistre l'etat d'une machine virtuelle lorsqu'elle est suspendue, pour pouvoir la reprendre plus tard dans le meme etat.",
  "Le fichier .vmss est lie a l'etat suspendu d'une machine virtuelle.": "VMSS signifie Virtual Machine Suspend State. Le fichier .vmss enregistre l'etat d'une machine virtuelle lorsqu'elle est suspendue, pour pouvoir la reprendre plus tard dans le meme etat.",
  "Une VM est suspendue. Quel fichier peut stocker son etat ?": "VMSS signifie Virtual Machine Suspend State. Le fichier .vmss enregistre l'etat d'une machine virtuelle lorsqu'elle est suspendue, pour pouvoir la reprendre plus tard dans le meme etat.",
  "Le fichier .vmsn contient :": "VMSN signifie Virtual Machine Snapshot Number. Le fichier .vmsn contient l'etat de la machine virtuelle au moment ou un snapshot est pris.",
  "VMSN signifie :": "VMSN signifie Virtual Machine Snapshot Number. Ce fichier contient l'etat de la VM au moment du snapshot.",
  "Le fichier .vmsd sert a :": "VMSD signifie Virtual Machine Snapshot Descriptor. Le fichier .vmsd sert a lister et organiser les snapshots d'une machine virtuelle.",
  "VMSD signifie :": "VMSD signifie Virtual Machine Snapshot Descriptor. Il sert a organiser et decrire les snapshots d'une machine virtuelle.",
  "Charger une configuration dans l'inventaire signifie :": "Dans VMware, la machine virtuelle existe physiquement dans le datastore sous forme de fichiers. Pour qu'elle apparaisse dans l'interface d'administration, il faut charger son fichier .vmx dans l'inventaire de l'hyperviseur.",
  "L'inventaire de l'hyperviseur est :": "Dans VMware, la machine virtuelle existe physiquement dans le datastore sous forme de fichiers. Pour qu'elle apparaisse dans l'interface d'administration, il faut charger son fichier .vmx dans l'inventaire de l'hyperviseur.",
  "L'inventaire VMware contient :": "Dans VMware, la machine virtuelle existe physiquement dans le datastore sous forme de fichiers. Pour qu'elle apparaisse dans l'interface d'administration, il faut charger son fichier .vmx dans l'inventaire de l'hyperviseur.",
  "Quand on dit qu'une VM est chargee dans l'inventaire, cela signifie :": "Dans VMware, la machine virtuelle existe physiquement dans le datastore sous forme de fichiers. Pour qu'elle apparaisse dans l'interface d'administration, il faut charger son fichier .vmx dans l'inventaire de l'hyperviseur.",
  "Une VM apparait dans le datastore mais pas dans l'interface VMware. Quelle action est la plus logique ?": "Dans VMware, la machine virtuelle existe physiquement dans le datastore sous forme de fichiers. Pour qu'elle apparaisse dans l'interface d'administration, il faut charger son fichier .vmx dans l'inventaire de l'hyperviseur.",
  "Un disque thick est un disque :": "Un disque thick est un disque statique : tout l'espace est reserve des la creation. Cela garantit l'espace et limite le risque de saturation imprevue du stockage.",
  "Avec un disque thick :": "Un disque thick est un disque statique : tout l'espace est reserve des la creation. Cela garantit l'espace et limite le risque de saturation imprevue du stockage.",
  "Quelles affirmations sur le disque thick sont vraies ?": "Un disque thick est un disque statique : tout l'espace est reserve des la creation. Cela garantit l'espace et limite le risque de saturation imprevue du stockage.",
  "Le thick provisioning reserve l'espace disque des la creation.": "Un disque thick est un disque statique : tout l'espace est reserve des la creation. Cela garantit l'espace et limite le risque de saturation imprevue du stockage.",
  "Un disque thin est :": "Un disque thin est un disque dynamique : il n'utilise que l'espace reellement consomme et grandit selon l'usage. Son principal avantage est l'economie d'espace, mais il faut surveiller le datastore pour eviter une saturation.",
  "L'avantage principal du thin provisioning est :": "Un disque thin est un disque dynamique : il n'utilise que l'espace reellement consomme et grandit selon l'usage. Son principal avantage est l'economie d'espace, mais il faut surveiller le datastore pour eviter une saturation.",
  "Le risque principal du thin provisioning est :": "Un disque thin est un disque dynamique : il n'utilise que l'espace reellement consomme et grandit selon l'usage. Son principal avantage est l'economie d'espace, mais il faut surveiller le datastore pour eviter une saturation.",
  "Parmi ces propositions, laquelle est correcte ?": "Un disque thin est un disque dynamique : il n'utilise que l'espace reellement consomme et grandit selon l'usage. Son principal avantage est l'economie d'espace, mais il faut surveiller le datastore pour eviter une saturation.",
  "Un disque thin :": "Un disque thin est un disque dynamique : il n'utilise que l'espace reellement consomme et grandit selon l'usage. Son principal avantage est l'economie d'espace, mais il faut surveiller le datastore pour eviter une saturation.",
  "Quelles affirmations sur le disque thin sont vraies ?": "Un disque thin est un disque dynamique : il n'utilise que l'espace reellement consomme et grandit selon l'usage. Son principal avantage est l'economie d'espace, mais il faut surveiller le datastore pour eviter une saturation.",
  "Le thin provisioning reserve tout l'espace du disque des la creation.": "Un disque thin est un disque dynamique : il n'utilise que l'espace reellement consomme et grandit selon l'usage. Son principal avantage est l'economie d'espace, mais il faut surveiller le datastore pour eviter une saturation.",
  "Quelle difference est correcte entre thick et thin ?": "La difference entre thick et thin est que le thick reserve l'espace disque des la creation, alors que le thin alloue l'espace progressivement selon l'usage reel.",
  "Tu crees un disque de 100 Go en thin. La VM contient seulement 18 Go de donnees. Que peut-on dire ?": "Un disque thin est un disque dynamique : il n'utilise que l'espace reellement consomme et grandit selon l'usage. Son principal avantage est l'economie d'espace, mais il faut surveiller le datastore pour eviter une saturation.",
  "L'initialisation d'un disque consiste a :": "L'initialisation consiste a mettre les blocs du disque a zero avant leur utilisation. Cela prepare correctement le disque virtuel.",
  "En Thick Eager Zeroed :": "En Thick Eager Zeroed, l'espace disque est reserve immediatement et tous les blocs sont initialises des la creation. Ce format est plus long a creer, mais le disque est entierement pret des le depart.",
  "Tu veux creer un disque entierement reserve et initialise immediatement. Quel type choisis-tu ?": "En Thick Eager Zeroed, l'espace disque est reserve immediatement et tous les blocs sont initialises des la creation. Ce format est plus long a creer, mais le disque est entierement pret des le depart.",
  "En Thick Lazy Zeroed :": "En Thick Lazy Zeroed, l'espace disque est reserve immediatement, mais les blocs ne sont initialises qu'au moment de leur premiere utilisation. Cela rend la creation plus rapide qu'en Eager Zeroed.",
  "Lequel cree le disque le plus rapidement ?": "En Thick Lazy Zeroed, l'espace disque est reserve immediatement, mais les blocs ne sont initialises qu'au moment de leur premiere utilisation. Cela rend la creation plus rapide qu'en Eager Zeroed.",
  "Quelle difference est correcte entre Thick Eager Zeroed et Thick Lazy Zeroed ?": "La difference entre Thick Eager Zeroed et Thick Lazy Zeroed concerne l'initialisation des blocs : en Eager Zeroed, tous les blocs sont mis a zero des la creation ; en Lazy Zeroed, ils le sont seulement au premier usage.",
  "Le swap sert a :": "Le swap est un espace disque utilise comme memoire temporaire lorsque la RAM n'est pas suffisante ou lorsque certaines donnees doivent etre deplacees hors de la memoire vive.",
  "Sous Windows, le fichier de swap est generalement :": "Sous Windows, le fichier de swap est generalement pagefile.sys. Il sert a etendre virtuellement la memoire lorsque la RAM ne suffit pas.",
  "Sous Linux, le swap peut etre :": "Sous Linux, le swap peut etre gere par une partition dediee ou par un fichier swap. Le principe reste le meme : utiliser du disque comme memoire temporaire.",
  "La suspension d'une VM permet :": "La suspension permet d'arreter temporairement l'execution d'une VM tout en conservant son etat exact. La machine peut ensuite reprendre la ou elle s'etait arretee.",
  "Un probleme de suspension ou de pause peut venir :": "Une VM peut rencontrer des problemes de pause, de suspension ou de fonctionnement si le datastore manque d'espace, si un mode veille est laisse actif ou si les fichiers necessaires comme le swap ou les snapshots ne peuvent plus etre geres correctement. Une VM suspendue trop longtemps peut aussi etre desynchronisee du reste de l'infrastructure.",
  "Une VM suspendue trop longtemps peut :": "Une VM peut rencontrer des problemes de pause, de suspension ou de fonctionnement si le datastore manque d'espace, si un mode veille est laisse actif ou si les fichiers necessaires comme le swap ou les snapshots ne peuvent plus etre geres correctement. Une VM suspendue trop longtemps peut aussi etre desynchronisee du reste de l'infrastructure.",
  "Une VM ne peut plus fonctionner correctement car le datastore est plein. Quelle cause est plausible ?": "Une VM peut rencontrer des problemes de pause, de suspension ou de fonctionnement si le datastore manque d'espace, si un mode veille est laisse actif ou si les fichiers necessaires comme le swap ou les snapshots ne peuvent plus etre geres correctement. Une VM suspendue trop longtemps peut aussi etre desynchronisee du reste de l'infrastructure.",
  "Un snapshot est :": "Un snapshot est une capture de l'etat d'une machine virtuelle a un instant T. Il permet un retour arriere apres un test, une modification ou une mise a jour, mais ce n'est pas une sauvegarde complete.",
  "Un snapshot sert principalement a :": "Un snapshot est une capture de l'etat d'une machine virtuelle a un instant T. Il permet un retour arriere apres un test, une modification ou une mise a jour, mais ce n'est pas une sauvegarde complete.",
  "Dans ton cours, il est recommande de ne pas garder un snapshot plus de :": "Un snapshot est une capture de l'etat d'une machine virtuelle a un instant T. Il permet un retour arriere apres un test, une modification ou une mise a jour, mais ce n'est pas une sauvegarde complete.",
  "Le snapshot n'est pas :": "Un snapshot est une capture de l'etat d'une machine virtuelle a un instant T. Il permet un retour arriere apres un test, une modification ou une mise a jour, mais ce n'est pas une sauvegarde complete.",
  "Le snapshot :": "Un snapshot est une capture de l'etat d'une machine virtuelle a un instant T. Il permet un retour arriere apres un test, une modification ou une mise a jour, mais ce n'est pas une sauvegarde complete.",
  "Quelles affirmations sur le snapshot sont vraies ?": "Un snapshot est une capture de l'etat d'une machine virtuelle a un instant T. Il permet un retour arriere apres un test, une modification ou une mise a jour, mais ce n'est pas une sauvegarde complete.",
  "Le snapshot est une sauvegarde complete de la machine virtuelle.": "Un snapshot est une capture de l'etat d'une machine virtuelle a un instant T. Il permet un retour arriere apres un test, une modification ou une mise a jour, mais ce n'est pas une sauvegarde complete.",
  "Quelle difference est correcte entre snapshot et sauvegarde ?": "Un snapshot est un point de retour temporaire, alors qu'une sauvegarde est une copie destinee a etre conservee et restauree si besoin. Un snapshot ne remplace donc pas une vraie sauvegarde.",
  "Un snapshot ne doit pas etre garde trop longtemps car :": "Un snapshot ne doit pas etre conserve trop longtemps, car il peut grossir, consommer beaucoup d'espace et degrader les performances. En production, on evite generalement de le garder plus de 24 heures.",
  "Un snapshot trop ancien peut poser probleme car :": "Un snapshot ne doit pas etre conserve trop longtemps, car il peut grossir, consommer beaucoup d'espace et degrader les performances. En production, on evite generalement de le garder plus de 24 heures.",
  "Le delta correspond :": "Le delta est le fichier qui enregistre les modifications effectuees apres la creation d'un snapshot. Tant que le snapshot existe, les nouvelles ecritures passent par ce fichier au lieu d'aller directement dans le disque principal.",
  "Apres creation d'un snapshot, ou vont les nouvelles modifications ?": "Le delta est le fichier qui enregistre les modifications effectuees apres la creation d'un snapshot. Tant que le snapshot existe, les nouvelles ecritures passent par ce fichier au lieu d'aller directement dans le disque principal.",
  "La consolidation permet :": "La consolidation permet de reintegrer les donnees du delta dans le disque principal de la machine virtuelle. Elle sert a remettre la VM dans un etat normal apres l'utilisation de snapshots.",
  "La consolidation consiste a :": "La consolidation permet de reintegrer les donnees du delta dans le disque principal de la machine virtuelle. Elle sert a remettre la VM dans un etat normal apres l'utilisation de snapshots.",
  "La consolidation permet de fusionner les donnees modifiees d'un snapshot avec le disque principal.": "La consolidation permet de reintegrer les donnees du delta dans le disque principal de la machine virtuelle. Elle sert a remettre la VM dans un etat normal apres l'utilisation de snapshots.",
  "Une VM a un snapshot ancien qui prend beaucoup de place. Quelle operation est la plus adaptee ?": "La consolidation permet de reintegrer les donnees du delta dans le disque principal de la machine virtuelle. Elle sert a remettre la VM dans un etat normal apres l'utilisation de snapshots.",
  "Un cluster de virtualisation est :": "Un cluster est un ensemble de plusieurs hotes de virtualisation regroupes pour fonctionner ensemble. Il permet de mutualiser les ressources, d'ameliorer la disponibilite, d'equilibrer la charge et de faciliter le deplacement des VM.",
  "Un cluster permet notamment :": "Un cluster est un ensemble de plusieurs hotes de virtualisation regroupes pour fonctionner ensemble. Il permet de mutualiser les ressources, d'ameliorer la disponibilite, d'equilibrer la charge et de faciliter le deplacement des VM.",
  "Dans un cluster, plusieurs hotes sont regroupes afin de :": "Un cluster est un ensemble de plusieurs hotes de virtualisation regroupes pour fonctionner ensemble. Il permet de mutualiser les ressources, d'ameliorer la disponibilite, d'equilibrer la charge et de faciliter le deplacement des VM.",
  "Quelles affirmations sur le cluster sont vraies ?": "Un cluster est un ensemble de plusieurs hotes de virtualisation regroupes pour fonctionner ensemble. Il permet de mutualiser les ressources, d'ameliorer la disponibilite, d'equilibrer la charge et de faciliter le deplacement des VM.",
  "Tu veux de la haute disponibilite et la possibilite de deplacer des VM entre plusieurs hotes. Quelle notion est la plus concernee ?": "Si on cherche la haute disponibilite, la repartition de charge et la possibilite de deplacer des VM entre plusieurs hotes, la notion cle est le cluster.",
  "La migration d'une VM consiste a :": "La migration d'une machine virtuelle consiste a la deplacer d'un hote a un autre. Cela peut servir a equilibrer la charge, faire de la maintenance ou ameliorer la disponibilite.",
  "La migration d'une VM peut etre utilisee pour :": "La migration d'une machine virtuelle consiste a la deplacer d'un hote a un autre. Cela peut servir a equilibrer la charge, faire de la maintenance ou ameliorer la disponibilite.",
  "Lequel est une solution de virtualisation open source ?": "Proxmox VE est une solution de virtualisation open source. Elle permet de gerer des machines virtuelles et des conteneurs via une interface web.",
  "Hyper-V est :": "Hyper-V est la solution de virtualisation de Microsoft. Elle permet de creer et gerer des machines virtuelles dans les environnements Windows.",
  "CPU signifie :": "CPU signifie Central Processing Unit. C'est le processeur, c'est-a-dire le composant qui execute les instructions.",
  "RAM signifie :": "RAM signifie Random Access Memory. C'est la memoire vive utilisee pour stocker temporairement les donnees et programmes en cours d'execution.",
  "Quels fichiers peuvent appartenir a une machine virtuelle VMware ?": "Une machine virtuelle VMware est composee de plusieurs fichiers. Par exemple, .vmx pour la configuration, .vmdk pour le disque, .nvram pour le BIOS/UEFI et .vswp pour le swap.",
  "Quelle difference est correcte entre hote et invite ?": "L'hote est le serveur physique ou l'hyperviseur qui heberge les machines virtuelles, tandis que l'invite est le systeme d'exploitation installe dans la VM."
};

const THICK_THIN_EXPLANATION = "Un disque virtuel peut etre cree selon plusieurs modes d'allocation d'espace. Un disque thick est un disque statique : tout l'espace du disque est reserve immediatement des la creation de la machine virtuelle. Avantages : espace garanti, meilleures performances generales, moins de risque de saturation imprevue. Inconvenient : il consomme tout l'espace des la creation. Un disque thin est un disque dynamique : il ne prend que l'espace reellement utilise et grandit progressivement selon les donnees stockees. Avantages : economie d'espace, plus grande souplesse, possibilite de creer plus de VM sur le meme stockage. Inconvenient : risque de saturation du datastore si plusieurs VM grandissent en meme temps. Le thin provisioning est automatiquement associe a un fonctionnement de type lazy zeroed.";
const ZEROED_EXPLANATION = "L'initialisation consiste a mettre les blocs du disque a zero avant leur utilisation. Elle sert a preparer le disque virtuel pour qu'il puisse etre utilise correctement par la machine virtuelle. En Thick Eager Zeroed, tout l'espace du disque est reserve immediatement et tous les blocs sont initialises des la creation. Avantages : disque entierement pret des le depart, utile pour certains environnements exigeants, necessaire pour certaines fonctionnalites avancees. Inconvenient : creation plus longue. En Thick Lazy Zeroed, l'espace est reserve immediatement, mais l'initialisation des blocs se fait seulement au moment ou ils sont utilises. Avantage : creation plus rapide. Inconvenient : initialisation progressive lors de l'usage.";
const SWAP_EXPLANATION = "Le swap est un espace disque utilise comme memoire temporaire lorsque la memoire vive n'est pas suffisante ou lorsque le systeme doit deplacer certaines donnees hors de la RAM. Sous Windows, le fichier de swap est generalement pagefile.sys. Sous Linux, le swap peut etre une partition swap ou un fichier swap. Sous VMware, le swap est gere avec le fichier .vswp. Dans ESXi, le fichier .vswp est cree au demarrage de la machine virtuelle et supprime a son arret.";

Object.assign(window.EXPLANATIONS_BY_PROMPT, {
  "Un disque thick est un disque :": THICK_THIN_EXPLANATION,
  "Avec un disque thick, l'espace disque est :": THICK_THIN_EXPLANATION,
  "Si on cree un disque de 100 Go en thick, que se passe-t-il ?": THICK_THIN_EXPLANATION,
  "Quel est un avantage du disque thick ?": THICK_THIN_EXPLANATION,
  "Quel est un inconvenient du disque thick ?": THICK_THIN_EXPLANATION,
  "Un disque thin est un disque :": THICK_THIN_EXPLANATION,
  "Avec un disque thin, l'espace disque :": THICK_THIN_EXPLANATION,
  "Si un disque de 100 Go en thin ne contient que 20 Go de donnees, il occupera environ :": THICK_THIN_EXPLANATION,
  "Quel est un avantage du disque thin ?": THICK_THIN_EXPLANATION,
  "Quel est un risque principal du thin provisioning ?": THICK_THIN_EXPLANATION,
  "Le thin provisioning est automatiquement associe a un fonctionnement de type :": THICK_THIN_EXPLANATION,
  "La principale difference entre un disque thick et un disque thin est que :": THICK_THIN_EXPLANATION,
  "Lequel de ces couples est correct ?": THICK_THIN_EXPLANATION,
  "Quelle affirmation est correcte ?": THICK_THIN_EXPLANATION,
  "Quels sont les avantages d'un disque thick ?": THICK_THIN_EXPLANATION,
  "Quels sont les avantages d'un disque thin ?": THICK_THIN_EXPLANATION,
  "Un disque thick est un disque dynamique.": THICK_THIN_EXPLANATION,
  "Un disque thin permet une economie d'espace.": THICK_THIN_EXPLANATION,
  "Le thin provisioning reserve tout l'espace des la creation.": THICK_THIN_EXPLANATION,
  "Tu crees un disque de 100 Go en thick. Quelle proposition est correcte ?": THICK_THIN_EXPLANATION,
  "Tu crees un disque de 100 Go en thin et tu y stockes 15 Go de donnees. Quelle proposition est correcte ?": THICK_THIN_EXPLANATION,
  "Plusieurs VM en thin grossissent en meme temps. Quel risque existe ?": THICK_THIN_EXPLANATION,
  "L'initialisation d'un disque consiste a :": ZEROED_EXPLANATION,
  "L'initialisation sert a :": ZEROED_EXPLANATION,
  "Dans le mode Thick Eager Zeroed :": ZEROED_EXPLANATION,
  "Un avantage du Thick Eager Zeroed est que :": ZEROED_EXPLANATION,
  "Quel est l'inconvenient principal du Thick Eager Zeroed ?": ZEROED_EXPLANATION,
  "Le Thick Eager Zeroed est utile :": ZEROED_EXPLANATION,
  "Dans le mode Thick Lazy Zeroed :": ZEROED_EXPLANATION,
  "Quel est l'avantage principal du Thick Lazy Zeroed ?": ZEROED_EXPLANATION,
  "Quel est l'inconvenient du Thick Lazy Zeroed ?": ZEROED_EXPLANATION,
  "La difference entre Thick Eager Zeroed et Thick Lazy Zeroed concerne principalement :": ZEROED_EXPLANATION,
  "En Thick Lazy Zeroed, les blocs sont mis a zero :": ZEROED_EXPLANATION,
  "En Thick Eager Zeroed, les blocs sont mis a zero :": ZEROED_EXPLANATION,
  "Quelle affirmation est correcte ?": ZEROED_EXPLANATION,
  "Quelles affirmations sur le Thick Eager Zeroed sont vraies ?": ZEROED_EXPLANATION,
  "Quelles affirmations sur le Thick Lazy Zeroed sont vraies ?": ZEROED_EXPLANATION,
  "Le Thick Eager Zeroed initialise les blocs des la creation du disque.": ZEROED_EXPLANATION,
  "Le Thick Lazy Zeroed initialise les blocs uniquement lorsqu'ils sont utilises.": ZEROED_EXPLANATION,
  "Tu veux un disque entierement pret des le depart, avec blocs deja initialises. Que choisis-tu ?": ZEROED_EXPLANATION,
  "Tu veux un disque thick cree plus rapidement, avec initialisation des blocs au premier usage. Que choisis-tu ?": ZEROED_EXPLANATION,
  "Le swap est :": SWAP_EXPLANATION,
  "Le swap est utilise lorsque :": SWAP_EXPLANATION,
  "Sous Windows, le fichier de swap est generalement :": SWAP_EXPLANATION,
  "Sous Linux, le swap peut etre :": SWAP_EXPLANATION,
  "Sous VMware, le swap est gere avec le fichier :": SWAP_EXPLANATION,
  "Dans ESXi, le fichier .vswp est :": SWAP_EXPLANATION,
  "Le fichier .vswp correspond :": SWAP_EXPLANATION,
  "Quelle affirmation est correcte a propos du swap ?": SWAP_EXPLANATION,
  "Quelles affirmations sur le swap sont vraies ?": SWAP_EXPLANATION,
  "Le swap est un espace disque utilise comme memoire temporaire.": SWAP_EXPLANATION,
  "Dans ESXi, le fichier .vswp est supprime a l'arret de la VM.": SWAP_EXPLANATION
});

window.EXPLANATION_SIGNATURES = {
  "Quelle affirmation est correcte ?||un disque thin reserve immediatement tout l'espace||un disque thick utilise seulement l'espace reellement consomme||un disque thin grandit selon les donnees stockees||un disque thick est toujours associe a un snapshot": THICK_THIN_EXPLANATION,
  "Quelle affirmation est correcte ?||le thick eager zeroed initialise les blocs des la creation||le thick lazy zeroed initialise tous les blocs avant creation||le thin provisioning reserve tout l'espace immediatement||le swap remplace le disque principal": ZEROED_EXPLANATION
};

